// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package com.overture.lib.subsystems.swerve;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.kinematics.SwerveDriveKinematics;
import edu.wpi.first.math.kinematics.SwerveModuleState;
import org.junit.jupiter.api.Test;

/**
 * Covers the skid detector.
 *
 * <p>Pure geometry, so unlike most of this library it runs without the HAL or Phoenix. The module
 * states are generated by WPILib's own kinematics, which means a consistent set really is
 * consistent rather than consistent by my arithmetic.
 */
class SkidDetectorTest {
  private static final Translation2d[] kModules = {
    new Translation2d(0.3, 0.3), // front left
    new Translation2d(0.3, -0.3), // front right
    new Translation2d(-0.3, 0.3), // back left
    new Translation2d(-0.3, -0.3) // back right
  };

  private static final SwerveDriveKinematics kKinematics = new SwerveDriveKinematics(kModules);

  private final SkidDetector detector = new SkidDetector(1.3, 0.1);

  @Test
  void agreeingModulesAreNotSkidding() {
    SwerveModuleState[] states = kKinematics.toSwerveModuleStates(new ChassisSpeeds(2.0, 0.0, 0.0));

    SkidDetector.Result result = detector.detect(states, kModules, 0.0);

    assertEquals(1.0, result.ratio, 1e-6, "modules driving in lockstep should agree exactly");
    assertFalse(result.skidding);
  }

  @Test
  void rotationIsSubtractedOutSoDrivingAndTurningStillAgrees() {
    // The case that separates this from naively comparing wheel speeds: turning while translating
    // makes the outer modules genuinely faster, and that is not a skid.
    ChassisSpeeds speeds = new ChassisSpeeds(2.0, 0.5, 1.5);
    SwerveModuleState[] states = kKinematics.toSwerveModuleStates(speeds);

    SkidDetector.Result result = detector.detect(states, kModules, speeds.omegaRadiansPerSecond);

    assertEquals(1.0, result.ratio, 1e-6, "the rotational part should cancel exactly");
    assertFalse(result.skidding);
    assertEquals(2.0, result.consensusVelocity.getX(), 1e-6);
    assertEquals(0.5, result.consensusVelocity.getY(), 1e-6);
  }

  @Test
  void spinningInPlaceReportsNothing() {
    ChassisSpeeds speeds = new ChassisSpeeds(0.0, 0.0, 4.0);
    SwerveModuleState[] states = kKinematics.toSwerveModuleStates(speeds);

    // Deliberately given a slightly wrong omega, so the cancellation leaves a small residue. With
    // no real translation to divide by, that residue would read as an enormous ratio.
    SkidDetector.Result result = detector.detect(states, kModules, 3.99);

    assertFalse(result.skidding, "a robot with no translation has nothing to disagree about");
  }

  @Test
  void aFastWheelIsFlaggedAndItIsTheRightOne() {
    ChassisSpeeds speeds = new ChassisSpeeds(2.0, 0.0, 0.0);
    SwerveModuleState[] states = kKinematics.toSwerveModuleStates(speeds);

    // Front right loses grip and overruns by half.
    states[1] = new SwerveModuleState(states[1].speedMetersPerSecond * 1.5, states[1].angle);

    SkidDetector.Result result = detector.detect(states, kModules, speeds.omegaRadiansPerSecond);

    assertTrue(result.skidding);
    assertEquals(1.5, result.ratio, 1e-6);
    assertFalse(result.skiddingModules[0]);
    assertTrue(result.skiddingModules[1], "the module reading high is the one that lost traction");
    assertFalse(result.skiddingModules[2]);
    assertFalse(result.skiddingModules[3]);
  }

  @Test
  void consensusIgnoresTheSkiddingModule() {
    ChassisSpeeds speeds = new ChassisSpeeds(2.0, 0.0, 0.0);
    SwerveModuleState[] states = kKinematics.toSwerveModuleStates(speeds);
    states[1] = new SwerveModuleState(states[1].speedMetersPerSecond * 1.5, states[1].angle);

    SkidDetector.Result result = detector.detect(states, kModules, speeds.omegaRadiansPerSecond);

    // Averaging all four would give 2.25 m/s, dragged up by the wheel that is lying.
    assertEquals(2.0, result.consensusVelocity.getX(), 1e-6);
  }

  @Test
  void aSlowWheelIsNotBlamed() {
    // A wheel dragging slower than the rest is being held back, not slipping. It still trips the
    // ratio, but it must not be the module we throw away, or odometry would follow the liars.
    ChassisSpeeds speeds = new ChassisSpeeds(2.0, 0.0, 0.0);
    SwerveModuleState[] states = kKinematics.toSwerveModuleStates(speeds);
    states[3] = new SwerveModuleState(states[3].speedMetersPerSecond * 0.5, states[3].angle);

    SkidDetector.Result result = detector.detect(states, kModules, speeds.omegaRadiansPerSecond);

    assertTrue(result.skidding);
    assertFalse(result.skiddingModules[3], "the slow module is not the one that lost traction");
    assertTrue(result.skiddingModules[0], "the three at full speed are the ones reading high");
  }
}
