name: Build Check

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  build-docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: wpilib/roborio-cross-ubuntu:2024-22.04
            artifact-name: Athena
            build-options: "-Ponlylinuxathena"
          # - container: wpilib/raspbian-cross-ubuntu:bullseye-22.04
          #   artifact-name: Arm32
          #   build-options: "-Ponlylinuxarm32"
          # - container: wpilib/aarch64-cross-ubuntu:bullseye-22.04
          #   artifact-name: Arm64
          #   build-options: "-Ponlylinuxarm64"
          - container: wpilib/ubuntu-base:22.04
            artifact-name: Linux
            build-options: ""
    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ubuntu-22.04
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Fetch all history and metadata
        run: |
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}

      - name: Ensure spotless is applied
        run: ./gradlew spotlessApply

      - name: Build with Gradle
        run: ./gradlew build -PreleaseMode ${{ matrix.build-options }}

  build-host:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            artifact-name: Win64
            architecture: x64
          - os: macos-15
            artifact-name: macOS
            architecture: x64
    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Fetch all history and metadata
        run: git fetch --prune --unshallow
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: ${{ matrix.architecture }}

      - name: Spotless Apply
        run : ./gradlew spotlessApply

      - name: Build with Gradle
        run: ./gradlew build -Pbuildalldesktop -PreleaseMode 
